- name: Build and Push Portfolio Docker Image
  hosts: localhost
  vars:
    release_version: "{{ lookup('env', 'RELEASE_VERSION') }}"
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"
  tasks:
    - name: Ensure frontend dist exists
      stat:
        path: portfolio-server/dist-frontend
      register: dist_dir

    - name: Fail if dist is missing
      fail:
        msg: "Frontend dist not found. Did you forget to upload/download artifact?"
      when: not dist_dir.stat.exists

    - name: Log into Dockerhub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Build and Push Docker image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/portfolio"
        source: build
        state: present
        build:
          path: portfolio-server
        tag: "{{ release_version }}"
        push: true


