- name: Build and Push Portfolio Docker Image
  hosts: localhost
  vars:
    release_version: "{{ lookup('env', 'RELEASE_VERSION') }}"
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"
  tasks:
    - name: Ensure frontend dist exists
      stat:
        path: portfolio-server/dist-frontend
      register: dist_dir

    - name: Fail if dist is missing
      fail:
        msg: "Frontend dist not found. Did you forget to upload/download artifact?"
      when: not dist_dir.stat.exists

    - name: Check dist-frontend contents
      shell: |
        cd portfolio-server
        ls -rtl dist-frontend

    - name: Build Docker image
      shell: |
        cd portfolio-server
        docker build -t {{ dockerhub_username }}/portfolio:{{ release_version }} .

    - name: Login to DockerHub
      shell: echo "{{ dockerhub_password }}" | docker login -u "{{ dockerhub_username }}" --password-stdin

    - name: Push Docker image
      shell: docker push {{ dockerhub_username }}/portfolio:{{ release_version }}
