- name: Build and Push Portfolio Docker Image
  hosts: localhost
  vars:
    release_version: "{{ lookup('env', 'RELEASE_VERSION') }}"
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"
  tasks:
    - name: Ensure frontend dist exists
      stat:
        path: portfolio-server/dist
      register: dist_dir

    - name: Fail if dist is missing
      fail:
        msg: "Frontend dist not found. Did you forget to upload/download artifact?"
      when: not dist_dir.stat.exists

    - name: Login to DockerHub
      shell: echo "{{ dockerhub_password }}" | docker login -u "{{ dockerhub_username }}" --password-stdin

    - name: Push Docker image
      shell: docker push {{ dockerhub_username }}/portfolio:{{ release_version }}

    - name: Build + Push Docker image
      community.docker.docker_image:
        name: "cuongnt02/portfolio"
        build:
          path: "portfolio-server"
        tag: "{{ backend_version }}"
        push: true
        source: build
